### ISSUE TITLE
Issue: Dark Power Relog

### ISSUE THREAD

**Issue by 0Bheka0** [DrasticDemiseFTBPacks/Banished#13] opened 2015-06-11 12:21 UTC
I observed this issue in at least 2 Dark Power Quests: Even though i already had enough to complete the quest upon accepting I needed to relog or gain Dark Power for the claim-button to become visible.

**Comment by 0Bheka0** [comment] 2015-06-11 12:37
Another Quest did not suffer this bug and I don't know why. First two were sapling and Magic Light Quests, the other was the first offensive spell quest.

**Comment by DrasticDemise** [comment] 2015-06-11 15:09
Hmm. That is interesting though I don't know if there is much I can do about it.

**Comment by Mechalith** [comment] 2015-06-11 19:09
It doesn't appear to actually need to change the Dark Power rep level. I had trouble getting 'the log quest' to register as complete, even though I was at the appropriate reputation level. Without the rep changing, it eventually went through.

I think the problem is just that HQM isn't necessarily checking your reputation levels immediately and only check at set intervals and when it rises or drops. Not sure there's anything you can do to change it though.

**Comment by DrasticDemise** [comment] 2015-06-11 19:11
I might be able to change the intervals at one lower so that it puts you one power ahead, that may force it to recognize you have enough.

**Comment by Mechalith** [comment] 2015-06-11 23:28
Correcting myself. It's not time, it's just a matter of closing and re-opening the quest book.

**Comment by DrasticDemise** [comment] 2015-06-12 00:43
So it is fixed by closing and reopening the quest book? If that is the case there isn't anything I can do about it.

**Comment by Mechalith** [comment] 2015-06-12 00:46
That would seem to be the case, yes. I'd go ahead and mark this 'closed/unresolvable', or something to that effect.

**Comment by DrasticDemise** [comment] 2015-06-12 01:08
Meh, if it can be solved without have to log/relog that is good enough for me. I will put a notice in the quest book.

**Closed as completed by DrasticDemise** 2015-06-12 01:08 UTC
Labels: bug, Can't fix
